---
sidebar: sidebar 
permalink: oci/add-credentials.html 
keywords: permissions, policy, iam, iam role, role, granting, iam policy, iam user, access keys, arn, aws accounts, aws, aws profile, json, credentials, adding credentials, add credentials, oci nss, oracle cloud infrastructure 
summary: 'Durch das Hinzufügen von Oracle Cloud Infrastructure (OCI)-Zugangsdaten verfügt Workload Factory über die erforderlichen Berechtigungen, um Cloud-Ressourcen in Ihren OCI-Konten einzusetzen und zu managen.' 
---
= Hinzufügen von Oracle Cloud Infrastructure-Anmeldeinformationen zu NetApp Workload Factory
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Das Hinzufügen und Managen Ihrer Cloud-Anbieter-Zugangsdaten stellt sicher, dass NetApp Workload Factory über die erforderlichen Berechtigungen verfügt, um Ressourcen in Ihren Cloud-Anbieterkonten einzusetzen und zu managen.

link:permissions-oci.html["Berechtigungen für OCI NetApp Storage Service"]

.Über diese Aufgabe
Auf der Seite „Credentials“ können Sie einem bestehenden Workload Factory Konto Zugangsdaten hinzufügen. Dadurch erhält Workload Factory die erforderlichen Berechtigungen, um Ressourcen und Prozesse in Ihrer Cloud-Umgebung zu managen.

.Bevor Sie beginnen
Sie benötigen Anmeldeinformationen, um sich bei Ihrem Oracle Cloud Infrastructure Konto anzumelden.

.Schritte
. Melden Sie sich bei der https://console.netapp.com/["NetApp Konsole"^]an.
. Im Menü erfolgt die Auswahl von *Workloads* > *Administration* > *Credentials*.
. Auf der Seite „Anmeldeinformationen“ ist die Option *Anmeldeinformationen hinzufügen* auszuwählen.
. Auf der Seite „Anmeldeinformationen für den Oracle Cloud Infrastructure NetApp Storage Service hinzufügen“ ist Folgendes auszuführen:
+
.. Unter „Berechtigungskonfiguration“ werden die entsprechenden Berechtigungen für die Anmeldeinformationen des Oracle Cloud Infrastructure NetApp Storage Service ausgewählt. *Anzeigen, planen und analysieren* ist die Standardberechtigung. Diese Berechtigungsrichtlinie ermöglicht das Anzeigen von OCI NSS Storage-Pools, Informationen zum Systemstatus, den Erhalt der Well-Architected-Analyse für Ihre Systeme und die Prüfung von Einsparpotenzialen.
.. Die mit der Oracle Cloud Console bereitgestellten manuellen Schritte ermöglichen das Abschließen der Berechtigungskonfiguration für die OCI NSS-Anmeldeinformationen.
.. Unter _Name der Anmeldeinformationen_ sind der Name einzugeben, der für diese Anmeldeinformationen verwendet werden soll, sowie die Mandanten-OCID.


. Wählen Sie *Add*.


.Was kommt als Nächstes
link:quick-start-oci.html["Schnellstart für Oracle Cloud Infrastructure NetApp Storage Service in NetApp Workload Factory."]
