---
sidebar: sidebar 
permalink: fsx-storage/create-discover-systems.html 
keywords: Amazon FSx for NetApp ONTAP, fsx, volumes, create system, delete system, access key, secret key, region, availability zones, discover, storage capacity, iops, throughput, security group, security, NetApp Console 
summary: Cloud Storage-Systeme erstellen oder entdecken, um Volumes und zusätzliche Datenservices über die NetApp Console hinzuzufügen und zu managen. 
---
= Cloud Storage-Systeme in NetApp Console erstellen oder erkennen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cloud Storage-Systeme erstellen oder entdecken, um Volumes und zusätzliche Datenservices über die NetApp Console hinzuzufügen und zu managen.



[[create-a-storage-system]]
== Ein Storage-System erstellen

Der erste Schritt besteht darin, ein Storage-System zu erstellen. Wenn Sie bereits ein Storage-System in der Konsole Ihres Cloud-Anbieters erstellt haben, können Sie <<Ein vorhandenes Cloud Storage-System entdecken,es mit der NetApp Console entdecken>>.

.Über diese Aufgabe
Eine Storage VM wird erstellt, wenn Sie ein Dateisystem erstellen.

.Bevor Sie beginnen
Bevor Sie Ihr FSx for ONTAP Dateisystem erstellen, benötigen Sie Folgendes:

* Der ARN einer IAM-Rolle, die Workload Factory die Berechtigungen erteilt, die zum Erstellen eines FSx for ONTAP Dateisystems erforderlich sind. link:permissions-reference-fsx.html["Erfahren Sie, wie Sie einem AWS-Konto Berechtigungen erteilen"^].
* Die Regions- und VPC-Informationen für den Ort, an dem Sie die FSx for ONTAP Instanz erstellen.




[[create-an-fsx-for-ontap-file-system]]
== Erstellen eines FSx for ONTAP Dateisystems

Sie können ein FSx for ONTAP Dateisystem mit _Quick create_ oder _Advanced create_ erstellen. Sie können auch die folgenden in der Codebox verfügbaren Tools verwenden: REST API, CloudFormation und Terraform. link:../admin/use-codebox.html#how-to-use-codebox["Informationen zur Verwendung von Codebox für die Automatisierung"^].


NOTE: Wenn Sie Terraform aus Codebox verwenden, werden im kopierten oder heruntergeladenen Code  `fsxadmin` und  `vsadmin` Passwörter ausgeblendet. Sie müssen die Passwörter erneut eingeben, wenn Sie den Code ausführen.

[role="tabbed-block"]
====
.Schnellerstellung
--
Mit Quick create können Sie eine empfohlene Best-Practice-Konfiguration verwenden. Die meisten Einstellungen können Sie nach dem Erstellen eines FSx for ONTAP file system ändern.

.Schritte
. Im Menü der NetApp Console werden *Storage* und dann *Management* ausgewählt.
. Auf der Seite „Systeme“ erfolgt die Auswahl der Option „System hinzufügen“.
. Als Standort wird *Amazon Web Services* ausgewählt und anschließend für Amazon FSx for NetApp ONTAP *Add new*.
. Auf der Seite „FSx for ONTAP Dateisystem erstellen“ erfolgt die Auswahl von *Quick create*.
+
Sie können auch eine gespeicherte Konfiguration laden.

. Unter „Allgemeine Dateisystemkonfiguration“ sind folgende Angaben erforderlich:
+
.. *AWS-Anmeldeinformationen*: Hier können Sie AWS-Anmeldeinformationen in Workload Factory hinzufügen oder ohne Anmeldeinformationen fortfahren.
.. *Dateisystemname*: Feld für die Eingabe eines Namens für das Dateisystem.
.. *Region & VPC*: Auswahl der Region und der VPC für das Dateisystem.
.. *Deployment-Typ*: Auswahl eines Deployment-Typs.
+
*** Single Availability Zone (Single-AZ) Deployment: stellt Verfügbarkeit durch die Überwachung von Hardwareausfällen und den automatischen Austausch von Infrastrukturkomponenten im Fehlerfall bereit. Erreicht eine hohe Ausfallsicherheit durch die automatische Replikation Ihrer Daten innerhalb einer Verfügbarkeitszone, um sie vor Komponentenausfällen zu schützen.
+
Diese Konfiguration wird für High-Performance-Workloads empfohlen oder wenn Workloads zunächst klein beginnen und schrittweise auf einen Durchsatz von 72 GB/s und 2,4 Millionen IOPS skalieren.

*** Deployment mit mehreren Availability Zones (Multi-AZ): gewährleistet die kontinuierliche Verfügbarkeit von Daten, selbst wenn eine Availability Zone nicht verfügbar ist. Ein Multi-AZ-Dateisystem ist für geschäftskritische Produktions-Workloads konzipiert, die eine hohe Verfügbarkeit gemeinsam genutzter ONTAP Dateidaten erfordern und Storage mit integrierter Replikation über Availability Zones hinweg benötigen.
+
Diese Konfiguration mit einem einzelnen HA-Paar wird für Workloads empfohlen, die einen Durchsatz von bis zu 6 GB/s oder 200.000 IOPS erfordern.



.. *Tags*: Optional können Sie bis zu 50 Tags hinzufügen.


. Unter *Dateisystemdetails* sind die folgenden Angaben erforderlich:
+
.. *SSD Storage-Kapazität*: Hier lassen sich die Speicherkapazität und die Einheit der Speicherkapazität angeben.
+
*** Bei Bereitstellungen der ersten Generation kann die Kapazität nach der Erstellung des Dateisystems nicht mehr verringert werden.
*** Bei Deployments der zweiten Generation können Sie die Kapazität nach der Erstellung des Dateisystems erhöhen.


.. *ONTAP-Zugangsdaten*: Optional. In diesem Schritt werden Ihr ONTAP-Benutzername und Ihr Passwort eingegeben. Das Passwort kann jetzt oder später festgelegt werden.
+
Falls der von Ihnen angegebene Benutzer nicht der fsxadmin-Benutzer ist und Sie später das fsxadmin-Passwort zurücksetzen müssen, können Sie dies über die AWS-Konsole tun.

.. *SMB/CIFS-Einrichtung*: Optional. Wenn Sie das SMB/CIFS-Protokoll für den Zugriff auf Volumes verwenden möchten, müssen Sie Active Directory für die Storage VM während der Dateisystemerstellung konfigurieren. Für die Storage VM, die für dieses Dateisystem erstellt wird, sind die folgenden Details erforderlich.
+
... *Active Directory-Domäne für den Beitritt*: Eingabe des vollqualifizierten Domainnamens (FQDN) für das Active Directory.
... *DNS-IP-Adressen*: Es können bis zu drei durch Kommas getrennte DNS-IP-Adressen eingegeben werden.
... *SMB Server NetBIOS-Name*: Der SMB Server NetBIOS-Name des Active Directory-Computerobjekts, das für Ihre Storage VM erstellt werden soll. Dies ist der Name dieser Storage VM im Active Directory.
... *Benutzername*: Hier wird der Benutzername des Dienstkontos in Ihrem bestehenden Active Directory eingegeben.
+
Die Eingabe erfolgt ohne Domänenpräfix oder -suffix. Für `EXAMPLE\ADMIN` kommt `ADMIN` zum Einsatz.

... *Passwort*: Das Passwort für das Dienstkonto eingeben.
... *Abteilung*: Optional können Sie den Namen der Abteilung eingeben, in der Sie das Computerkonto für FSx for ONTAP erstellen möchten. Die OU ist der eindeutige Pfadname der Abteilung, mit der Sie das Dateisystem verknüpfen möchten.
... *Delegierte Administratorengruppe*: Optional können Sie den Namen der Gruppe in Ihrem Active Directory eingeben, die Ihr Dateisystem verwalten kann.
+
Wenn Sie AWS Managed Microsoft AD verwenden, müssen Sie eine Gruppe wie AWS Delegated FSx Administrators, AWS Delegated Administrators oder eine benutzerdefinierte Gruppe mit delegierten Berechtigungen für die Abteilung angeben.

+
Wenn Sie einem selbstverwalteten AD beitreten, verwenden Sie den Namen der Gruppe in Ihrem AD. Die Standardgruppe ist `Domain Admins`.





. In der *Zusammenfassung* lässt sich die von Ihnen definierte Konfiguration überprüfen. Bei Bedarf können Sie jetzt vor dem Speichern oder Erstellen des Dateisystems jede Einstellung ändern.
. Speichern oder Erstellen des Dateisystems.


.Ergebnis
Wenn Sie das Dateisystem erstellt haben, erscheint die neue FSx for ONTAP Konfiguration auf der Seite „Systeme“.

Es gibt verschiedene Möglichkeiten, Ihre FSx for ONTAP Dateisysteme zu managen, etwa über Workloads in der NetApp Console, mit ONTAP System Manager und mit AWS CloudFormation.

--
.Erweiterte Erstellung
--
Mit Advanced create legen Sie alle Konfigurationsoptionen fest, einschließlich Verfügbarkeit, Sicherheit, Backups und Wartung.

.Schritte
. Im Menü der NetApp Console werden *Storage* und dann *Management* ausgewählt.
. Auf der Seite „Systeme“ erfolgt die Auswahl der Option „System hinzufügen“.
. Als Standort wird *Amazon Web Services* ausgewählt und anschließend für Amazon FSx for NetApp ONTAP *Add new*.
. Auf der Seite „FSx for ONTAP Dateisystem erstellen“ ist *Advanced create* auszuwählen.
+
Sie können auch eine gespeicherte Konfiguration laden.

. Unter „Allgemeine Dateisystemkonfiguration“ sind folgende Angaben erforderlich:
+
.. *AWS-Anmeldeinformationen*: Hier können Sie AWS-Anmeldeinformationen in Workload Factory hinzufügen oder ohne Anmeldeinformationen fortfahren.
.. *Dateisystemname*: Feld für die Eingabe eines Namens für das Dateisystem.
.. *Region & VPC*: Auswahl der Region und der VPC für das Dateisystem.
.. *Deployment-Typ*: Auswahl eines Deployment-Typs und der Dateisystemgeneration. Die Verfügbarkeit eines Dateisystems der zweiten Generation hängt von der ausgewählten Region ab. Wenn die ausgewählte Region keine FSx for ONTAP Dateisysteme der zweiten Generation unterstützt, wird der Deployment-Typ auf die erste Generation umgestellt.
+
*** Single Availability Zone (Single-AZ) Deployment: stellt Verfügbarkeit durch die Überwachung von Hardwareausfällen und den automatischen Austausch von Infrastrukturkomponenten im Fehlerfall bereit. Erreicht eine hohe Ausfallsicherheit durch die automatische Replikation Ihrer Daten innerhalb einer Verfügbarkeitszone, um sie vor Komponentenausfällen zu schützen.
+
*Dateisystemgenerierung*: Eine der folgenden Optionen ist auszuwählen:

+
**** *Zweite Generation*: Diese Konfiguration wird für Workloads mit hoher Performance oder für Workloads empfohlen, die klein beginnen und schrittweise auf einen Durchsatz von 72 GB/s und 2,4 Millionen IOPS skalieren.
**** *Erste Generation*: Diese Konfiguration eignet sich ideal für Workloads, die bis zu 4 GB/s oder 160.000 IOPS benötigen. Dateisysteme der ersten Generation können nur die Kapazität erhöhen.


*** Deployment mit mehreren Availability Zones (Multi-AZ): gewährleistet die kontinuierliche Verfügbarkeit von Daten, selbst wenn eine Availability Zone nicht verfügbar ist. Ein Multi-AZ-Dateisystem ist für geschäftskritische Produktions-Workloads konzipiert, die eine hohe Verfügbarkeit gemeinsam genutzter ONTAP Dateidaten erfordern und Storage mit integrierter Replikation über Availability Zones hinweg benötigen.
+
*Dateisystemgenerierung*: Eine der folgenden Optionen ist auszuwählen:

+
**** *Zweite Generation*: Diese Konfiguration mit einem einzelnen HA-Paar wird für Workloads empfohlen, die einen Durchsatz von bis zu 6 GB/s oder 200.000 IOPS erfordern. In einer Multi-AZ-Umgebung und einem Dateisystem der zweiten Generation kann die Kapazität je nach Workload-Anforderungen erhöht oder verringert werden.
**** *Erste Generation*: Diese Konfiguration eignet sich ideal für Workloads, die bis zu 4 GB/s oder 160.000 IOPS benötigen. Dateisysteme der ersten Generation können nur die Kapazität erhöhen.




.. *Tags*: Optional können Sie bis zu 50 Tags hinzufügen.


. Unter Dateisystemdetails sind die folgenden Angaben erforderlich:
+
.. *SSD Storage-Kapazität*: Hier lassen sich die Speicherkapazität und die Einheit der Speicherkapazität angeben.
+
*** Bei Bereitstellungen der ersten Generation kann die Kapazität nach der Erstellung des Dateisystems nicht mehr verringert werden.
*** Bei Deployments der zweiten Generation lässt sich die Kapazität anpassen.


.. *Durchsatzkapazität pro HA-Paar*: Auswahl der Durchsatzkapazität entsprechend der Anzahl der HA-Paare. Dateisysteme der ersten Generation unterstützen nur ein HA-Paar.
.. *Bereitgestellte IOPS*: Zur Auswahl steht eine der folgenden Optionen:
+
*** *Automatisch*: Bei der automatischen Einstellung werden für jedes erstellte GiB 3 IOPS hinzugefügt.
*** *Benutzerseitig bereitgestellt*: Für „Benutzerseitig bereitgestellt“ wird der IOPS-Wert eingegeben.


.. *ONTAP-Zugangsdaten*: Optional. In diesem Schritt werden Ihr ONTAP-Benutzername und Ihr Passwort eingegeben. Das Passwort kann jetzt oder später festgelegt werden.
+
Falls der von Ihnen angegebene Benutzer nicht der fsxadmin-Benutzer ist und Sie später das fsxadmin-Passwort zurücksetzen müssen, können Sie dies über die AWS-Konsole tun.

.. *Anmeldeinformationen der Storage VM*: Optional. Eintrag Ihres Benutzernamens. Das Passwort kann spezifisch für dieses Dateisystem sein, oder es kann dasselbe Passwort verwendet werden, das für die ONTAP-Anmeldeinformationen eingegeben wurde. Das Passwort kann jetzt oder später festgelegt werden.
.. *SMB/CIFS-Einrichtung*: Optional. Wenn Sie das SMB/CIFS-Protokoll für den Zugriff auf Volumes verwenden möchten, müssen Sie Active Directory für die Storage VM während der Dateisystemerstellung konfigurieren. Für die Storage VM, die für dieses Dateisystem erstellt wird, sind die folgenden Details erforderlich.
+
... *Active Directory-Domäne für den Beitritt*: Eingabe des vollqualifizierten Domainnamens (FQDN) für das Active Directory.
... *DNS-IP-Adressen*: Es können bis zu drei durch Kommas getrennte DNS-IP-Adressen eingegeben werden.
... *SMB Server NetBIOS-Name*: Der SMB Server NetBIOS-Name des Active Directory-Computerobjekts, das für Ihre Storage VM erstellt werden soll. Dies ist der Name dieser Storage VM im Active Directory.
... *Benutzername*: Hier wird der Benutzername des Dienstkontos in Ihrem bestehenden Active Directory eingegeben.
+
Die Eingabe erfolgt ohne Domänenpräfix oder -suffix. Für `EXAMPLE\ADMIN` kommt `ADMIN` zum Einsatz.

... *Passwort*: Das Passwort für das Dienstkonto eingeben.
... *Abteilung*: Optional können Sie den Namen der Abteilung eingeben, in der Sie das Computerkonto für FSx for ONTAP erstellen möchten. Die OU ist der eindeutige Pfadname der Abteilung, mit der Sie das Dateisystem verknüpfen möchten.
... *Delegierte Administratorengruppe*: Optional können Sie den Namen der Gruppe in Ihrem Active Directory eingeben, die Ihr Dateisystem verwalten kann.
+
Wenn Sie AWS Managed Microsoft AD verwenden, müssen Sie eine Gruppe wie AWS Delegated FSx Administrators, AWS Delegated Administrators oder eine benutzerdefinierte Gruppe mit delegierten Berechtigungen für die Abteilung angeben.

+
Wenn Sie einem selbstverwalteten AD beitreten, verwenden Sie den Namen der Gruppe in Ihrem AD. Die Standardgruppe ist `Domain Admins`.





. Unter Netzwerk & Sicherheit sind die folgenden Angaben erforderlich:
+
.. *Sicherheitsgruppe*: Eine neue Sicherheitsgruppe erstellen oder eine vorhandene verwenden.
+
Informationen zu den Sicherheitsgruppenprotokollen, Ports und Rollen einer neuen Sicherheitsgruppe finden Sie unter <<Security group details,Details zur Sicherheitsgruppe>>.

.. *Verfügbarkeitszonen*: Auswahl von Verfügbarkeitszonen und Subnetzen.
+
*** Für Knoten 1 der Clusterkonfiguration: Es sind eine Verfügbarkeitszone und ein Subnetz auszuwählen.
*** Für den Clusterkonfigurationsknoten 2 erfolgt die Auswahl einer Verfügbarkeitszone und eines Subnetzes.


.. *VPC Routentabellen*: Unter *VPC Routentabellen* wird die VPC Routentabelle ausgewählt, um den Clientzugriff auf Volumes zu aktivieren.
.. *Endpunkt-IP-Adressbereich*: Für den *Endpunkt-IP-Adressbereich* ist *Floating IP address range outside your VPC* oder *Enter an IP address range* auszuwählen und ein IP-Adressbereich einzugeben.
.. *Verschlüsselung*: Auswahl des Namens des Verschlüsselungsschlüssels aus der Dropdown-Liste.


. Unter „Datensicherung und Wartung“ sind folgende Angaben erforderlich:
+
.. *Volume-Backups*: Tägliche automatische Backups sind standardmäßig aktiviert. Deaktivieren, falls gewünscht.
+
... *Aufbewahrungsdauer für automatische Backups*: Geben Sie die Anzahl der Tage an, für die automatische Backups aufbewahrt werden sollen.
... *Tägliches automatisches Sicherungsfenster*: Zur Auswahl stehen *Keine Präferenz* (eine tägliche Sicherungsstartzeit wird für Sie ausgewählt) oder *Startzeit für tägliche Sicherungen auswählen*; anschließend ist eine Startzeit anzugeben.


.. *Wöchentliches Wartungsfenster*: Zur Auswahl stehen entweder *Keine Präferenz* (eine Startzeit für das wöchentliche Wartungsfenster wird für Sie ausgewählt) oder *Startzeit für 30-minütiges wöchentliches Wartungsfenster*; zusätzlich ist eine Startzeit anzugeben.


. Speichern oder Erstellen des Dateisystems.


.Ergebnis
Wenn Sie das Dateisystem erstellt haben, erscheint die neue FSx for ONTAP Konfiguration auf der Seite „Systeme“.

Es gibt verschiedene Möglichkeiten, Ihre FSx for ONTAP Dateisysteme zu managen, etwa über Workloads in der NetApp Console, mit ONTAP System Manager und mit AWS CloudFormation.

--
====


[[discover-an-existing-cloud-storage-system]]
== Ein vorhandenes Cloud Storage-System entdecken

Wenn Sie Ihre Zugangsdaten für Ihren Cloud-Storage-Anbieter zuvor in Workload Factory angegeben haben, können Sie Ihre Storage-Systeme auf der Seite Discoverable systems automatisch erkennen. Dort können Sie auch verfügbare Datenservices prüfen.

.Über diese Aufgabe
Sie können ein Cloud Storage-System innerhalb eines Kontos nur einmal erkennen und es einem Arbeitsbereich zuordnen. Das Storage-System kann später entfernt und einem anderen Arbeitsbereich neu zugeordnet werden.

.Schritte
. Im Menü NetApp Console erfolgt die Auswahl von *Storage*, dann *Management* und anschließend *Discoverable systems*.
. Die Anzahl der ermittelten Cloud Storage-Systeme wird angezeigt. Die Auswahl erfolgt über *Discover*.
. Zum Hinzufügen zur Seite „Systeme“ ist die Auswahl eines oder mehrerer Storage-Systeme und von *Discover* erforderlich.


[NOTE]
====
* Wenn Sie ein unbenanntes Storage-System auswählen, erhalten Sie eine Aufforderung, einen Namen für das System einzugeben.
* Wenn Sie ein Storage-System auswählen, für dessen Management über die Console nicht die erforderlichen Anmeldeinformationen vorhanden sind, wird eine Aufforderung angezeigt, Anmeldeinformationen mit den erforderlichen Berechtigungen auszuwählen.
* Für die Erkennung werden die folgenden Regionen nicht unterstützt: Regionen in China, GovCloud (US) Regionen, Secret Cloud und Top Secret Cloud.


====
.Ergebnis
Die Console zeigt Ihr erkanntes System auf der Seite „Systeme“ an. Sie können Ihre Storage-Systeme auf verschiedene Weise managen, beispielsweise über Workloads in der NetApp Console sowie mit ONTAP System Manager oder mit den Storage-Management-Tools Ihres Cloud-Providers.
