= Erstveröffentlichung von Oracle Cloud Infrastructure NetApp Storage Service für Workload Factory
:allow-uri-read: 




[[initial-release-of-oracle-cloud-infrastructure-netapp-storage-service-for-workload-factory]]
=== Erstveröffentlichung von Oracle Cloud Infrastructure NetApp Storage Service für Workload Factory

Die erste Version des OCI NetApp Storage Service (OCI NSS) für Workload Factory bietet Onboarding, Systemerkennung, Anmeldeinformationsverwaltung sowie die Erstellung und Zuordnung von Links. Für die Beantragung des Zugriffs auf OCI NSS ist ein Support-Ticket bei Oracle erforderlich.



[[workload-factory-documentation-for-netapp-console-users]]
=== Workload Factory Dokumentation für NetApp Console Benutzer

Detaillierte Dokumentation für Workload Factory finden Sie in der NetApp Console, einschließlich Anleitungen für Onboarding, Systemerkennung, Management von Anmeldeinformationen sowie Erstellung und Zuordnung von Links.

link:https://docs.netapp.com/us-en/data-services-workloads/index.html["Workload Factory Dokumentation für NetApp Console"]
