---
sidebar: sidebar 
permalink: gcnv/add-credentials.html 
keywords: permissions, policy, iam, iam role, role, granting, iam policy, iam user, access keys, arn, aws accounts, aws, aws profile, json, credentials, adding credentials, add credentials 
summary: Durch das Hinzufügen der Anmeldeinformationen für Google Cloud NetApp Volumes erhält Workload Factory die erforderlichen Berechtigungen, um Cloud-Ressourcen in Ihren Google-Konten einzusetzen und zu managen. 
---
= Hinzufügen von Google Cloud NetApp Volumes Anmeldedaten zu NetApp Workload Factory
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Das Hinzufügen und Managen Ihrer Cloud-Anbieter-Zugangsdaten stellt sicher, dass NetApp Workload Factory über die erforderlichen Berechtigungen verfügt, um Ressourcen in Ihren Cloud-Anbieterkonten einzusetzen und zu managen.



[[overview]]
== Überblick

Sie können die Anmeldeinformationen für Google Cloud NetApp Volumes auf der Seite „Anmeldeinformationen“ in der NetApp console hinzufügen. Die Konsole bietet eine geführte Einrichtungsanleitung und einen Link zur Dokumentation, sodass Sie die erforderliche Google Cloud-Konfiguration abschließen und anschließend zurückkehren können, um das Hinzufügen der Anmeldeinformationen abzuschließen.

Mit diesem Workflow erhält Workload Factory die Berechtigungen, die zum Erkennen, Analysieren und Managen von Ressourcen in Ihrer Google Cloud-Umgebung erforderlich sind.

Die Erstellung der Zugangsdaten besteht aus drei Teilen:

* Schritt 1: Auswahl des Berechtigungsstufen-Levels, das Sie Workload Factory gewähren möchten.
* Schritt 2: Erstellen und Validieren eines Google Cloud-Dienstkontos sowie anschließendes Auswählen des zu managenden Google Cloud-Projekts.
* Schritt 3: Eingabe eines Namens für die Anmeldeinformationen sowie Hinzufügen der Anmeldeinformationen.


.Bevor Sie beginnen
Sie benötigen Anmeldeinformationen, um sich bei Ihrem Google Cloud Konto anzumelden.

.Schritte
. Melden Sie sich bei der https://console.netapp.com/["NetApp Konsole"^]an.
. Im Menü erfolgt die Auswahl von *Workloads* > *Administration* > *Credentials*.
. Auf der Seite „Anmeldeinformationen“ ist die Option *Anmeldeinformationen hinzufügen* auszuwählen.
. *Google Cloud NetApp Volumes* ist als Cloud-Anbieter auszuwählen.
. Auf der Seite zum Hinzufügen von Google Cloud NetApp Volumes Anmeldeinformationen ist jeder Abschnitt unter *Berechtigungskonfiguration* auszufüllen.




[[step-1-create-permission-policies]]
=== Schritt 1: Berechtigungsrichtlinien erstellen

.Schritte
. Unter *Berechtigungsrichtlinien erstellen* ist *Anzeigen, planen und analysieren* standardmäßig ausgewählt. Diese Berechtigungsrichtlinie ermöglicht es Ihnen, die Storage Pools von Google Cloud NetApp Volumes anzuzeigen, Informationen zum Systemstatus zu erhalten, die Well-Architected-Analyse für Ihre Systeme abzurufen und Einsparpotenziale zu ermitteln.
. Optional: *Betrieb und Fehlerbehebung* auswählen, wenn Workload Factory auch Google Cloud NetApp Volumes Ressourcen managen und Konfigurationsprobleme beheben soll.
. Vor dem Fortfahren empfiehlt sich ein Blick auf die Einrichtungsanweisungen unter link:https://docs.netapp.com/us-en/storage-management-google-cloud-netapp-volumes/task-set-up-gcnv.html#set-up-a-service-account["Einrichtung von Google Cloud NetApp Volumes"^].




[[step-2-create-the-google-cloud-service-account]]
=== Schritt 2: Erstellen des Google Cloud Dienstkontos

.Schritte
. Abschnitt *Google Cloud-Umgebung einrichten* erweitern.
. Die angezeigten Schritte 1-5 müssen abgeschlossen werden, um ein Google Cloud-Dienstkonto zu erstellen.
. Die E-Mail-Adresse des Servicekontos kopieren.
. Nach der Rückkehr zu Workload Factory können Sie die E-Mail-Adresse in das Feld *GCP service account* einfügen und *Validate credentials* auswählen.
. Nach Abschluss der Validierung erfolgt im Dropdown-Menü *Projects* die Auswahl des Google Cloud-Projekts, das Workload Factory managen soll. HINWEIS: Die Projects-Liste ist erst verfügbar, nachdem die Anmeldeinformationen des Dienstkontos überprüft wurden.




[[step-3-enter-the-credentials-name]]
=== Schritt 3: Den Namen der Anmeldeinformationen eingeben

.Schritte
. *Name der Anmeldeinformationen* erweitern.
. Im Feld *Name* wird ein Name für die Anmeldedaten mit ausschließlich alphanumerischen Zeichen eingegeben. Sonderzeichen und Leerzeichen sind nicht zulässig.
. Wählen Sie *Add*.


.Ergebnis
Die Anmeldeinformationen für Google Cloud NetApp Volumes wurden Ihrem Konto hinzugefügt und stehen für unterstützte Workload Factory-Vorgänge zur Verfügung.
