---
sidebar: sidebar 
permalink: admin/manage-credentials.html 
keywords: aws accounts, aws, credentials, edit credentials, manage credentials, delete credentials 
summary: Wenn Sie Anmeldeinformationen nicht mehr benötigen, können Sie diese aus NetApp Workload Factory löschen. Sie können nur Anmeldeinformationen löschen, die nicht mit einem FSx for ONTAP-Dateisystem verknüpft sind. 
---
= Entfernen von Anmeldeinformationen aus NetApp Workload Factory
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Wenn Sie Anmeldeinformationen nicht mehr benötigen, können Sie diese in Workload Factory löschen. Sie können nur Anmeldeinformationen löschen, die nicht mit einem FSx for ONTAP Dateisystem verknüpft sind.

.Schritte
. Melden Sie sich bei der link:https://console.netapp.com["NetApp Console"^] an.
. Im Menü der NetApp Console erfolgt die Auswahl von *Workloads* > *Administration* > *Credentials*.
. Auf der Seite *Anmeldeinformationen* sind folgende Schritte erforderlich:
+
** In der Workload Factory Konsole wird im Aktionsmenü für einen Satz Anmeldeinformationen die Option *Remove* ausgewählt. Zur Bestätigung wird *Remove* ausgewählt.
** In der NetApp Console wählen Sie für einen Satz von Anmeldeinformationen das Aktionsmenü und anschließend *Delete* aus. Wählen Sie zur Bestätigung *Delete* aus.



