---
sidebar: sidebar 
permalink: fsx-vmware/deploy-fsx-file-system-evs.html 
keywords: vm workloads, deploy fsx, deploy storage for vms, evs, elastic vmware service 
summary: Nachdem Sie überprüft haben, ob das empfohlene FSx for ONTAP Dateisystem bzw. in einigen Fällen die empfohlenen Dateisysteme Ihren genauen Anforderungen entsprechen, lässt sich Workload Factory zum Einsatz des Systems in Ihrer AWS-Umgebung verwenden. 
---
= Einsatz des empfohlenen FSx for ONTAP Dateisystems
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie überprüft haben, dass das empfohlene FSx for ONTAP Dateisystem (oder in einigen Fällen mehrere Dateisysteme) Ihren genauen Anforderungen entspricht, können Sie Workload Factory verwenden, um das System in Ihrer AWS-Umgebung einzusetzen.

Abhängig von den Richtlinien und Berechtigungen, die Sie Ihrem Workload Factory Konto hinzugefügt haben, können Sie das FSx for ONTAP Dateisystem vollständig mit Workload Factory einsetzen (im lesen/schreiben Modus). Wenn Sie über weniger Berechtigungen (schreibgeschützter Modus) oder keine Berechtigungen (Basic Modus) verfügen, müssen Sie die CloudFormation Vorlage aus der Codebox verwenden und das FSx for ONTAP Dateisystem selbst in AWS einsetzen.



[[requirements]]
== Anforderungen

* Sie benötigen ein Abonnement für Amazon Elastic VMware Service.
* Sie benötigen die erforderlichen Berechtigungen, um ein FSx for ONTAP Dateisystem in Ihrem AWS-Konto zu erstellen.




[[considerations]]
== Überlegungen

* Sie können die Option „Schnell erstellen“ oder „Erweitert erstellen“ verwenden. „Erweitert erstellen“ bietet einige zusätzliche Storage-Parameter, die Sie anpassen können. link:../fsx-storage/create-discover-systems.html["Was diese beiden Optionen bieten"].
* Im Abschnitt „Amazon Elastic VMware Service preferences“ können Sie die EVS Virtualisierungsumgebung auswählen, um die Verbindung zu den externen Datenspeichern herzustellen. Dadurch werden einige Felder automatisch mit den Best-Practice-Optionen für das Deployment ausgefüllt. Diese Optionen können Sie nach Bedarf anpassen.




[[steps]]
== Schritte

. Am unteren Rand der Seite *Review plan* führt die Auswahl von *Deploy* zur Anzeige der Seite „Create an FSx for ONTAP file system“.
+
Die meisten Felder, die Ihr FSx for ONTAP Dateisystem definieren, sind anhand der von Ihnen bereitgestellten Informationen ausgefüllt. Es gibt jedoch einige Felder, die Sie auf dieser Seite ausfüllen müssen.

. Im Abschnitt „Allgemeine Konfiguration des Dateisystems“ erfolgt die Eingabe der folgenden Informationen:
+
.. *AWS-Anmeldeinformationen*: Wählen Sie Anmeldeinformationen aus oder fügen Sie sie hinzu, die Workload Factory die erforderlichen Berechtigungen erteilen, um Ihr FSx for ONTAP file system direkt zu erstellen. Alternativ können Sie auch den CloudFormation Code aus Codebox auswählen und das FSx for ONTAP file system in AWS selbst einsetzen.
.. *Dateisystemname*: Geben Sie den Namen ein, den Sie für dieses FSx for ONTAP Dateisystem verwenden möchten.
.. *Tags*: Optional können Sie Tags hinzufügen, um dieses FSx for ONTAP Dateisystem zu kategorisieren.


. Im Abschnitt „Amazon Elastic VMware Service Einstellungen“ erfolgt die Auswahl der EVS-Umgebung, an die die Datastores angebunden werden, in der Liste „Environment ID“.
+
Dadurch werden die folgenden Felder automatisch ausgefüllt:

+
** *VPC*
** *Verfügbarkeitszone*
** *Subnetz*
** Im Abschnitt *NFS-Datenspeicherzugriff* füllt das System das Feld *EVS-Hostverwaltung (CIDR)* automatisch aus, wenn Sie die Option *Nur EVS-Hostverwaltung* ausgewählt haben.
** Im Abschnitt *Datastore-Einbindungsoptionen* werden die Felder *EVS Cluster VMware vCenter-Adresse* und *vSphere Administratoranmeldeinformationen Secret ARN* automatisch ausgefüllt, wenn Sie ausgewählt haben, Datastores im EVS Cluster einzubinden.


. Im Abschnitt „Netzwerk & Sicherheit“ erfolgt die Eingabe der folgenden Informationen:
+
.. *Region & VPC*: Auswahl der Region und der VPC, in der das Dateisystem FSx for ONTAP eingesetzt wird.
.. *Sicherheitsgruppe* (nur erweiterte Erstellung): Bei Verwendung der Option *Erweiterte Erstellung* können Sie die Standard-Sicherheitsgruppe für die FSx for ONTAP VPC auswählen, sodass der gesamte Datenverkehr auf das FSx for ONTAP Dateisystem zugreifen kann. Sie können entweder eine neue Sicherheitsgruppe erstellen oder eine vorhandene auswählen.
+
Wenn Sie die Option *Sicherheitsgruppenkonfiguration an EVS NFS Datenspeicher anpassen* aktivieren, konfiguriert Workload Factory die Sicherheitsgruppe gemäß den Einstellungen für EVS NFS Datenspeicher.

+
Sie können der Sicherheitsgruppe eine eingehende Regel hinzufügen, die einschränkt, auf welche anderen AWS Services das FSx for ONTAP Dateisystem zugreifen kann. Dadurch wird die Anzahl der offenen Services reduziert. Dies sind die minimalen Ports und Protokolle:

+
[cols="15,10,55"]
|===
| Protokolle | Ports | Zweck 


| TCP, UDP | 111 | Portmapper (zum Aushandeln der in NFS-Anfragen verwendeten Ports) 


| TCP, UDP | 635 | NFS mountd (empfängt NFS-Mount-Anfragen) 


| TCP, UDP | 2049 | NFS Netzwerkdatenverkehr 


| TCP, UDP | 4045 | Network Lock Manager (NLM, lockd) - Verarbeitet Sperranforderungen. 


| TCP, UDP | 4046 | Netzwerkstatusmonitor (NSM, statd) - Benachrichtigt NFS-Clients über Neustarts des Servers für die Sperrverwaltung. 
|===
.. *Verfügbarkeitszone*: Die Verfügbarkeitszone und das Subnetz werden ausgewählt.
+
Sie sollten dieselbe Verfügbarkeitszone auswählen, in der Ihr VMware SDDC bereitgestellt ist, wenn Sie Gebühren für Cross-AZ-Datenverkehr vermeiden möchten.

.. *Encryption* (nur bei *Advanced create*): Bei Verwendung der Option *Advanced create* können Sie den Namen des AWS-Verschlüsselungsschlüssels aus der Dropdown-Liste auswählen.
.. *NFS Datastores Zugriff* (nur bei *Advanced create*): Bei Verwendung der Option *Advanced create* können Sie auswählen, ob alle Hosts auf die Datastores zugreifen können oder ob nur der EVS Management Host auf die Datastores zugreifen kann.


. Im Abschnitt „Dateisystemdetails“ erfolgt die Eingabe der folgenden Informationen:
+
.. *ONTAP Zugangsdaten*: Eingabe von ONTAP Benutzername und Passwort.
.. *Anmeldeinformationen für die Storage VM* (nur bei erweiterter Erstellung): Geben Sie das Kennwort für die Storage VM ein und bestätigen Sie es. Das Kennwort kann spezifisch für dieses Dateisystem sein, oder Sie können dasselbe Kennwort verwenden, das Sie für die ONTAP Anmeldeinformationen eingegeben haben.


. Im Abschnitt „EVS Cluster Anbindung“ sind die folgenden Informationen einzugeben:
+
.. *Datastore-Einbindungsoptionen*: Optional kann die Option *Datastores in den EVS Cluster einbinden* aktiviert werden, um die Datastores automatisch mit dem Amazon EVS Cluster zu verbinden. Diese Option bewirkt außerdem, dass Workload Factory die VMware ESXi Hosteinstellungen so konfiguriert, dass sie den ONTAP Best-Practice-Empfehlungen entsprechen. Vor dem Einsatz des Dateisystems können die Plandetails im Abschnitt *Summary* geprüft werden, um die geänderten Einstellungen zu sehen.
.. *EVS Cluster vSphere Konsolendetails*: IP-Adresse oder FQDN des VMware vCenter Servers, der eine Verbindung zu Amazon EVS herstellen soll.
.. *vSphere Administratoranmeldeinformationen Secret ARN*: Hier wird der Secret ARN für die Administratoranmeldeinformationen von vSphere ausgewählt. Diese Anmeldeinformationen werden verwendet, um Datastores einzubinden und empfohlene VMware-Einstellungen zu konfigurieren.
+
Falls Amazon EVS in dieser Region nicht verfügbar ist oder Ihr Konto nicht über die Berechtigungen zum Abrufen der Liste der verfügbaren secret ARNs verfügt, können Sie einen secret ARN-Wert manuell eingeben.



. Im Abschnitt *Summary* ist die FSx for ONTAP Dateisystem- und Datastore-Konfiguration zu sehen, die der VMware Migration Advisor auf Basis Ihrer Angaben entworfen hat.
. Über *Erstellen* lässt sich das Dateisystem FSx for ONTAP einsetzen. Dieser Vorgang kann bis zu 2 Stunden dauern.
+
Im Codebox-Fenster steht optional die Option *Umleiten nach CloudFormation* zur Verfügung, mit der sich das Dateisystem und die empfohlene VM-Konfiguration mithilfe eines CloudFormation Stack erstellen lassen.

+
In beiden Fällen können Sie den Erstellungsfortschritt in CloudFormation überwachen.





[[result]]
== Ergebnis

Das FSx for ONTAP Dateisystem ist bereitgestellt. Sie können nun die AWS CloudFormation Vorlage in der Codebox verwenden, um die empfohlene VM-Konfiguration in Ihrer Amazon Elastic VMware Service Umgebung einzusetzen.
