---
sidebar: sidebar 
permalink: fsx-vmware/deploy-fsx-file-system.html 
keywords: vm workloads, deploy fsx, deploy storage for vms 
summary: Nachdem Sie überprüft haben, ob das empfohlene FSx for ONTAP Dateisystem bzw. in einigen Fällen die empfohlenen Dateisysteme Ihren genauen Anforderungen entsprechen, lässt sich Workload Factory zum Einsatz des Systems in Ihrer AWS-Umgebung verwenden. 
---
= Einsatz des empfohlenen FSx for ONTAP Dateisystems
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie überprüft haben, dass das empfohlene FSx for ONTAP Dateisystem (oder in einigen Fällen mehrere Dateisysteme) Ihren genauen Anforderungen entspricht, können Sie Workload Factory verwenden, um das System in Ihrer AWS-Umgebung einzusetzen.

Abhängig von den Richtlinien und Berechtigungen, die Sie Ihrem Workload Factory Konto hinzugefügt haben, können Sie das FSx for ONTAP Dateisystem vollständig mit Workload Factory einsetzen (im Modus lesen/schreiben). Wenn Sie über weniger Berechtigungen (Nur-Lese-Modus) oder keine Berechtigungen (Basismodus) verfügen, müssen Sie die CloudFormation Informationen aus der Codebox verwenden und das FSx for ONTAP Dateisystem selbst in AWS einsetzen.

.Anforderungen für Deployments in VMware Cloud on AWS
* Sie müssen VMware Cloud on AWS Software-Defined Data Center (SDDC) Version 1.20 oder höher verwenden, um FSx for ONTAP Dateisysteme einzusetzen.
* Das FSx for ONTAP Dateisystem darf nicht in derselben VPC eingesetzt werden, die während des SDDC Deployment verwendet wurde. Stattdessen muss es in einer neuen Amazon VPC eingesetzt werden, die Ihnen gehört, um die Integration von VMware Cloud on AWS mit Amazon FSx for NetApp ONTAP zu ermöglichen.
* Sie müssen das Dateisystem FSx for ONTAP in derselben AWS Region wie Ihr SDDC einsetzen.


.Schritte
. Am unteren Rand der Seite *Review plan* führt die Auswahl von *Deploy* zur Anzeige der Seite „Create an FSx for ONTAP file system“.
+
Die meisten Felder, die Ihr FSx for ONTAP Dateisystem definieren, sind anhand der von Ihnen bereitgestellten Informationen ausgefüllt. Es gibt jedoch einige Felder, die Sie auf dieser Seite ausfüllen müssen.

+
Sie können die Option „Schnell erstellen“ oder „Erweitert erstellen“ verwenden. „Erweitert erstellen“ bietet einige zusätzliche Storage-Parameter, die Sie anpassen können. link:../fsx-storage/create-discover-systems.html["Was diese beiden Optionen bieten"].

. *AWS-Anmeldeinformationen*: Wählen Sie Anmeldeinformationen aus oder fügen Sie sie hinzu, die Workload Factory die erforderlichen Berechtigungen erteilen, um Ihr FSx for ONTAP file system direkt zu erstellen. Alternativ können Sie auch den CloudFormation Code aus Codebox auswählen und das FSx for ONTAP file system in AWS selbst einsetzen.
. *Dateisystemname*: Geben Sie den Namen ein, den Sie für dieses FSx for ONTAP Dateisystem verwenden möchten.
. *Tags*: Optional können Sie Tags hinzufügen, um dieses FSx for ONTAP Dateisystem zu kategorisieren.
. Im Abschnitt „Netzwerk & Sicherheit“ erfolgt die Eingabe der folgenden Informationen:
+
.. *Region & VPC*: Auswahl der Region und der VPC, in der das FSx for ONTAP Dateisystem eingesetzt wird.
+
Beim Einsatz von VMware Cloud on AWS sollte das Deployment in einer anderen VPC als der VPC erfolgen, in der VMware Cloud on AWS eingesetzt wird.

.. *Sicherheitsgruppe*: Bei Verwendung der Option *Erweitert erstellen* können Sie die Standard-Sicherheitsgruppe für die FSx for ONTAP VPC auswählen, sodass der gesamte Datenverkehr auf das FSx for ONTAP Dateisystem zugreifen kann.
+
Zum Einschränken des Zugriffs anderer AWS Services auf das Dateisystem FSx for ONTAP kann eine eingehende Regel hinzugefügt werden. Dadurch wird die Anzahl offener Services begrenzt. Dies sind die minimal erforderlichen Ports und Protokolle:

+
[cols="15,10,55"]
|===
| Protokolle | Ports | Zweck 


| TCP, UDP | 111 | Portmapper (zum Aushandeln der in NFS-Anfragen verwendeten Ports) 


| TCP, UDP | 635 | NFS mountd (empfängt NFS-Mount-Anfragen) 


| TCP, UDP | 2049 | NFS Netzwerkdatenverkehr 


| TCP, UDP | 4045 | Network Lock Manager (NLM, lockd) - Verarbeitet Sperranforderungen. 


| TCP, UDP | 4046 | Netzwerkstatusmonitor (NSM, statd) - Benachrichtigt NFS-Clients über Neustarts des Servers für die Sperrverwaltung. 
|===
.. *Verfügbarkeitszone*: Auswahl der Verfügbarkeitszone und des Subnetzes.
+
Sie sollten dieselbe Verfügbarkeitszone auswählen, in der Ihr VMware SDDC bereitgestellt ist, wenn Sie Gebühren für Cross-AZ-Datenverkehr vermeiden möchten.

.. *Verschlüsselung*: Bei Verwendung der Option *Advanced create* können Sie den Namen des AWS-Verschlüsselungsschlüssels aus der Dropdown-Liste auswählen.
.. *Zugriffskontrolle für Datenspeicher*: Bei Verwendung der Option *Erweiterte Erstellung* können Sie auswählen, ob alle Hosts auf die Datenspeicher zugreifen können oder ob nur bestimmte vSphere Clusterknoten in einem bestimmten Subnetz auf die Datenspeicher zugreifen können.


. Im Abschnitt „Dateisystemdetails“ erfolgt die Eingabe der folgenden Informationen:
+
.. *ONTAP Zugangsdaten*: Eingabe und Bestätigung des ONTAP Passworts.
.. *Anmeldeinformationen für die Storage VM* (nur bei erweiterter Erstellung): Geben Sie das Kennwort für die Storage VM ein und bestätigen Sie es. Das Kennwort kann spezifisch für dieses Dateisystem sein, oder Sie können dasselbe Kennwort verwenden, das Sie für die ONTAP Anmeldeinformationen eingegeben haben.


. Im Abschnitt *Summary* ist die FSx for ONTAP Dateisystem- und Datastore-Konfiguration zu sehen, die der VMware Migration Advisor auf Basis Ihrer Angaben entworfen hat.
. Über *Erstellen* lässt sich das Dateisystem FSx for ONTAP einsetzen. Dieser Vorgang kann bis zu 2 Stunden dauern.
+
Optional können Sie im Codebox-Fenster die Option *Umleiten nach CloudFormation* auswählen, um das Dateisystem mithilfe eines CloudFormation Stack zu erstellen.

+
In beiden Fällen können Sie den Erstellungsfortschritt in CloudFormation überwachen.



.Ergebnis
Das FSx for ONTAP Dateisystem wird eingesetzt.
